import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sidebar } from "../components/Sidebar/Sidebar";
import { ThemeProv } from "@/components/Theme/ThemeProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" style={{ colorScheme: "light" }}>
      <body className={inter.className}>
        <ThemeProv>
          <div className="flex h-screen">
            <Sidebar />
            <div className="w-full">{children}</div>
          </div>
        </ThemeProv>
      </body>
    </html>
  );
}
